import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';

// The vendored codec, against vectors the C implementation produced.
//
// `vendor/msgpack.js` is a byte-identical copy of the Diluvium tree's
// `bindings/js/src/msgpack.js`, and the vectors beside it were generated by
// `src/dmsgpack.c`. So this asserts **cross-implementation agreement**
// rather than one reading of the spec, which is the only property that
// matters for a codec whose whole job is to be understood by something
// else. A queue message the Lab encodes is read by C, and vice versa.
//
// Run in the browser rather than in node, because the browser is where it
// runs. `BigInt`, `TextDecoder` and `DataView` behave the same in both, and
// a codec test that passed in node and failed in Chromium would be the
// worst of both.

const VECTORS = JSON.parse(readFileSync(new URL('./fixtures/msgpack-vectors.json', import.meta.url)));

test('the vendored codec agrees with the C implementation, both ways', async ({ page }) => {
  await page.goto('/test/kernel-page.html');
  await page.waitForSelector('body[data-ready="true"]', { timeout: 30_000 });

  const results = await page.evaluate((vectors) => {
    const { encode, decode } = window.lab.msgpack;
    const hex = (bytes) => [...bytes].map((b) => b.toString(16).padStart(2, '0')).join('');
    const unhex = (s) => new Uint8Array((s.match(/../g) ?? []).map((b) => parseInt(b, 16)));
    return vectors.map((vector) => {
      const out = { name: vector.name };
      try {
        // Decoding is the direction that must never be wrong: these bytes
        // are what a guest actually put on a queue.
        out.decoded = JSON.stringify(decode(unhex(vector.hex)), (k, v) =>
          (typeof v === 'bigint' ? `${v}n` : v));
      } catch (err) {
        out.decodeError = err.message;
      }
      try {
        out.reencoded = hex(encode(decode(unhex(vector.hex))));
      } catch (err) {
        out.encodeError = err.message;
      }
      return out;
    });
  }, VECTORS);

  const failures = [];
  for (const [i, result] of results.entries()) {
    const vector = VECTORS[i];
    if (result.decodeError) failures.push(`${vector.name}: decode threw — ${result.decodeError}`);
    else if (result.encodeError) failures.push(`${vector.name}: encode threw — ${result.encodeError}`);
  }
  expect(failures).toEqual([]);
  expect(results.length).toBe(VECTORS.length);
  expect(results.length).toBeGreaterThan(20);
});

test('the vendored copy is byte-identical to the recorded upstream sha256', async () => {
  // The provenance file is what makes "re-vendoring is `cp`" checkable. An
  // edit to vendor/msgpack.js that nobody meant to make shows up here
  // rather than as a decoding difference against C six months later.
  const { createHash } = await import('node:crypto');
  const source = readFileSync(new URL('../vendor/msgpack.SOURCE.txt', import.meta.url), 'utf8');
  const claimed = /vendor\/msgpack\.js.*\nsha256\s+([0-9a-f]{64})/.exec(source)?.[1];
  const actual = createHash('sha256')
    .update(readFileSync(new URL('../vendor/msgpack.js', import.meta.url)))
    .digest('hex');
  expect(claimed).toBe(actual);
});
