#!/usr/bin/env bash
#
# Pin a Diluvium runtime into vendor/.
#
#   scripts/fetch-runtime.sh [tag]        default: v5.5.1_build2
#
# Downloads the kernel module plus the release's checksum and build
# manifest, and verifies the module against the former. This is the
# Stage 2 mechanism in miniature -- the version dropdown does the same
# three steps in the browser.
#
# Pulls from the mirror by default. Set DILUVIUM_RELEASE_BASE to point
# somewhere else -- notably at GitHub, which is where a build the mirror
# does not carry lives:
#
#   DILUVIUM_RELEASE_BASE=https://github.com/Aloecraft-org/diluvium/releases/download \
#     scripts/fetch-runtime.sh v5.5.1_build3
#
# This used to say that only v5.4.7_release attaches libdiluvium_wasi.wasm
# to its GitHub release. That is no longer true: build1, build2 and build3
# all do. What GitHub does not do is send Access-Control-Allow-Origin, so
# the *browser* still needs the mirror even though curl does not.
#
# Which tags the mirror should carry is not a judgement call -- it is
# `mirror_tags` in the Diluvium repository's changelog.json, and
# scripts/build-mirror.sh reads it. v5.5.1_build3 is deliberately not in
# that set: it is a prerelease whose supported configuration is narrower
# than the feature set it ships. Pin it if you want what it added; do not
# pin it by default.

set -euo pipefail

TAG="${1:-v5.5.1_build2}"
MIRROR="${DILUVIUM_RELEASE_BASE:-https://diluvium.aloecraft.org/release}"
BASE="$MIRROR/$TAG"
DEST="$(cd "$(dirname "$0")/.." && pwd)/vendor"

mkdir -p "$DEST"

for f in libdiluvium_wasi.wasm SHA256SUMS.txt BUILDINFO.txt; do
  echo "fetching $f ..."
  curl -fsSL --retry 3 -o "$DEST/$f" "$BASE/$f"
done

expected=$(grep ' libdiluvium_wasi\.wasm$' "$DEST/SHA256SUMS.txt" | cut -d' ' -f1)
actual=$(sha256sum "$DEST/libdiluvium_wasi.wasm" | cut -d' ' -f1)

if [ -z "$expected" ]; then
  echo "error: libdiluvium_wasi.wasm not listed in SHA256SUMS.txt" >&2
  exit 1
fi
if [ "$expected" != "$actual" ]; then
  echo "error: checksum mismatch" >&2
  echo "  expected $expected" >&2
  echo "  actual   $actual" >&2
  exit 1
fi

printf '%s\n' "$TAG" > "$DEST/PINNED_TAG"

# The same facts as a module, so the page can state exactly which build it
# is running without a fetch or a parse. BUILDINFO.txt is the source: it
# carries the version the release job recorded, which is not always
# derivable from the tag.
version=$(sed -n 's/^version *: *//p' "$DEST/BUILDINFO.txt" | head -1)
commit=$(sed -n 's/^commit *: *//p' "$DEST/BUILDINFO.txt" | head -1)
built=$(sed -n 's/^built *: *//p' "$DEST/BUILDINFO.txt" | head -1)

cat > "$DEST/pinned.js" <<EOF
// Generated by scripts/fetch-runtime.sh. Do not edit.
//
// The bundled Diluvium, stated rather than guessed at. Imported as a
// module so the page needs no fetch and no parsing to say what it runs --
// which matters because this is the first thing a bug report should carry.

export const BUNDLED = {
  tag: '$TAG',
  version: '$version',
  commit: '$commit',
  built: '$built',
  sha256: '$actual',
  artifact: 'libdiluvium_wasi.wasm',
};
EOF

echo "ok: $TAG pinned, sha256 $actual"
echo "    wrote vendor/pinned.js ($version, commit ${commit:0:12})"
