#!/usr/bin/env bash
#
# Pin a Diluvium runtime into vendor/.
#
#   scripts/fetch-runtime.sh [tag]        default: v5.5.1_build1
#
# Downloads the kernel module plus the release's checksum and build
# manifest, and verifies the module against the former. This is the
# Stage 2 mechanism in miniature -- the version dropdown does the same
# three steps in the browser.
#
# Pulls from the mirror rather than from GitHub, because the mirror is
# where the artifacts reliably are: of the tags that exist upstream, only
# v5.4.7_release attaches libdiluvium_wasi.wasm to its GitHub release, and
# v5.5.1_build1 -- the one you most likely want -- does not. Set
# DILUVIUM_RELEASE_BASE to point somewhere else.

set -euo pipefail

TAG="${1:-v5.5.1_build1}"
MIRROR="${DILUVIUM_RELEASE_BASE:-https://diluvium.aloecraft.org/release}"
BASE="$MIRROR/$TAG"
DEST="$(cd "$(dirname "$0")/.." && pwd)/vendor"

mkdir -p "$DEST"

for f in libdiluvium_wasi.wasm SHA256SUMS.txt BUILDINFO.txt; do
  echo "fetching $f ..."
  curl -fsSL --retry 3 -o "$DEST/$f" "$BASE/$f"
done

expected=$(grep ' libdiluvium_wasi\.wasm$' "$DEST/SHA256SUMS.txt" | cut -d' ' -f1)
actual=$(sha256sum "$DEST/libdiluvium_wasi.wasm" | cut -d' ' -f1)

if [ -z "$expected" ]; then
  echo "error: libdiluvium_wasi.wasm not listed in SHA256SUMS.txt" >&2
  exit 1
fi
if [ "$expected" != "$actual" ]; then
  echo "error: checksum mismatch" >&2
  echo "  expected $expected" >&2
  echo "  actual   $actual" >&2
  exit 1
fi

printf '%s\n' "$TAG" > "$DEST/PINNED_TAG"

# The same facts as a module, so the page can state exactly which build it
# is running without a fetch or a parse. BUILDINFO.txt is the source: it
# carries the version the release job recorded, which is not always
# derivable from the tag.
version=$(sed -n 's/^version *: *//p' "$DEST/BUILDINFO.txt" | head -1)
commit=$(sed -n 's/^commit *: *//p' "$DEST/BUILDINFO.txt" | head -1)
built=$(sed -n 's/^built *: *//p' "$DEST/BUILDINFO.txt" | head -1)

cat > "$DEST/pinned.js" <<EOF
// Generated by scripts/fetch-runtime.sh. Do not edit.
//
// The bundled Diluvium, stated rather than guessed at. Imported as a
// module so the page needs no fetch and no parsing to say what it runs --
// which matters because this is the first thing a bug report should carry.

export const BUNDLED = {
  tag: '$TAG',
  version: '$version',
  commit: '$commit',
  built: '$built',
  sha256: '$actual',
  artifact: 'libdiluvium_wasi.wasm',
};
EOF

echo "ok: $TAG pinned, sha256 $actual"
echo "    wrote vendor/pinned.js ($version, commit ${commit:0:12})"
