// Put the version in every module URL, so a cache cannot serve half a build.
//
//   node scripts/stamp-imports.mjs        rewrite the import map in index.html
//   node scripts/stamp-imports.mjs --check   fail if it is out of date
//
// ## Why
//
// The served page has no build step, so module URLs carry no content hash.
// A CDN or a browser holding `src/app.js` from an older deploy has no way
// to know it is stale, and nothing throws when it is -- the old code simply
// lacks the newer half of the page. That produced a genuinely
// undiagnosable failure: fresh HTML, stale modules, clean console.
//
// Appending `?v=<version>` fixes it outright, because a different URL is a
// different cache entry. The obstacle is that static `import` specifiers
// cannot be rewritten at runtime, and a query on the entry point does not
// propagate -- a relative import inside `app.js` resolves against
// `/src/app.js`, dropping the query.
//
// An **import map** solves exactly this. It lives in index.html, which is
// the one file always fetched fresh, and it can remap resolved URLs. So
// every module in the graph gets a versioned URL, and bumping the version
// invalidates the whole graph atomically.
//
// This runs at release time, not development time. The un-bundled page
// still runs as-is from a checkout: the map points at the same files with
// a query the server ignores.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';

const ROOT = new URL('../', import.meta.url);
const INDEX = new URL('index.html', ROOT);
const START = '<!-- BEGIN import map: generated by scripts/stamp-imports.mjs -->';
const END = '<!-- END import map -->';

const check = process.argv.includes('--check');

const html = await readFile(INDEX, 'utf8');
const version = /export const LAB_VERSION = '([^']+)'/
  .exec(await readFile(new URL('src/version.js', ROOT), 'utf8'))?.[1];
if (!version) {
  console.error('stamp-imports: could not read LAB_VERSION from src/version.js');
  process.exit(1);
}

/**
 * Every relative specifier in a source file, static and dynamic alike.
 *
 * The `new URL` branch captures the leading dots rather than eating one of
 * them. It used to match `['"`]\.` and capture what followed, which handed
 * the walk `/kernel-worker.js` for `'./kernel-worker.js'` — a specifier
 * that does not start with a dot and was therefore dropped by the guard
 * below. So that branch had never contributed anything, quietly, and the
 * first `new URL('../../…')` in the tree turned the same off-by-one into a
 * wrong path instead of no path, which is how it was noticed.
 */
const SPECIFIERS = /(?:import|export)\s[^;]*?from\s*['"]([^'"]+)['"]|import\(\s*['"]([^'"]+)['"]|new URL\(\s*['"`](\.[^'"`?]*)/g;

/**
 * Walk the graph the way the browser does, from index.html outwards.
 *
 * `new URL(...)` is matched deliberately: that is how the worker script is
 * named. It is pulled into the graph so that its own imports get stamped
 * and so a missing file is caught, even though the map cannot govern how
 * the worker itself is fetched -- `new Worker()` happens outside module
 * resolution, so that URL is versioned by hand at its use site.
 *
 * The honest limit: **a module worker does not inherit the document's
 * import map.** Its own imports resolve unversioned, so the five modules
 * behind the kernel can still be served stale to the worker even when the
 * main thread has fresh copies. The worker script itself is versioned, so
 * this is a smaller window than it was, and a kernel that misbehaves
 * falls back to running in the page -- but it is not nothing, and the
 * real fix remains the host not caching unversioned scripts.
 *
 * Two kinds of thing are reached and then **not walked into**, both for
 * the same reason -- what is inside them is not this page's module graph:
 *
 *   `vendor/`  verbatim third-party bundles. Emscripten's loader builds a
 *              `new URL(".", …)` at *runtime* to find its own directory,
 *              which is not a build-time reference to anything and which
 *              this walk would otherwise chase to a directory.
 *   non-`.js`  the wasm binary beside the vendored SQLite. An import map
 *              governs module resolution and nothing else, so an entry
 *              for it would be an instruction with no reader.
 *
 * Both are still checked for existence, because catching a reference to a
 * file nobody vendored is half of why this walk exists.
 */
async function graph() {
  const found = new Set();
  const queue = [['./index.html', '/']];
  while (queue.length) {
    const [spec, from] = queue.pop();
    if (!spec.startsWith('.')) continue;
    const path = resolve(dirname(from), spec);
    if (found.has(path)) continue;

    const isModule = path.endsWith('.js');
    if (isModule) found.add(path);
    if (path !== '/index.html' && (!isModule || path.startsWith('/vendor/'))) {
      await readFile(new URL(`.${path}`, ROOT)).catch(() => {
        console.error(`stamp-imports: ${path} is referenced but missing`);
        process.exit(1);
      });
      continue;
    }

    let source;
    try {
      source = await readFile(new URL(`.${path}`, ROOT), 'utf8');
    } catch {
      console.error(`stamp-imports: ${path} is imported but missing`);
      process.exit(1);
    }
    for (const match of source.matchAll(SPECIFIERS)) {
      const next = match[1] ?? match[2] ?? match[3];
      if (next) queue.push([next, path]);
    }
  }
  return [...found].sort();
}

const modules = await graph();
const imports = Object.fromEntries(modules.map((p) => [`.${p}`, `.${p}?v=${version}`]));
const block = [
  START,
  '<script type="importmap">',
  JSON.stringify({ imports }, null, 2),
  '</script>',
  END,
].join('\n');

const existing = html.includes(START)
  ? html.slice(html.indexOf(START), html.indexOf(END) + END.length)
  : null;

if (check) {
  if (existing === block) {
    console.log(`stamp-imports: up to date (${modules.length} modules at v${version})`);
    process.exit(0);
  }
  console.error('stamp-imports: index.html\'s import map is out of date.');
  console.error('  Run: node scripts/stamp-imports.mjs');
  console.error(existing === null
    ? '  (there is no import map in index.html at all)'
    : `  (expected ${modules.length} modules at v${version})`);
  process.exit(1);
}

const updated = existing === null
  // Immediately before the module that starts everything, which is the
  // only ordering an import map permits.
  ? html.replace('<script type="module">', `${block}\n<script type="module">`)
  : html.replace(existing, block);

await writeFile(INDEX, updated);
console.log(`stamp-imports: ${modules.length} modules stamped v${version}`);
for (const path of modules.slice(0, 3)) console.log(`  .${path} -> .${path}?v=${version}`);
if (modules.length > 3) console.log(`  ... and ${modules.length - 3} more`);
